sudo: required

services:
  - docker

env:
#  - LANGUAGE=cwl
  - LANGUAGE=wdl
#  - LANGUAGE=nfl

# notifications:
#   slack: 
#     on_success: never
#     on_failure: always
#     rooms:
#       - oicr:S9k4EowgQv9AnbCfEZHSzCsg

language: java
jdk: 
  - openjdk8

before_install:
  - docker build -t quay.io/ilya_broad/dockstore-tool-selscan .
#  - pyenv global 3.6

install: 
  - bash install.sh

script: 
  - bash script.sh
